### ISSUE TITLE
[photon] Failed to flash <photon_id>: Permission Denied

### ISSUE THREAD

**Issue by hysteria9** [particle-iot/device-os#2261]
### Expected Behavior

I get trouble to flash my program to my photon using the new firmware 2.0.1. I tried flashing using particle cli and particle workbench on vs code but both returned me the same result. 
I also performed a particle doctor in order to reset everything but my wifi credentials, but it is still not working.
Note that neither OTA flashing nor USB flashing is running. When I locally try to flash it, the device is "not found", meaning that it cannot go to DFU mode...

[update]
 I also tried with another photon and with a different FW version (1.5.2) but it is still the same result. It seems to be something wrong with my particle dev environment but I don't know what ...
Any ideas ?

### Observed Behavior

What it returned when I try to flash :

```plain-text
attempting to flash firmware to your device <photon_id>
Failed to flash <photon_id>: Permission Denied
    at makeError (c:\Users\user\.vscode\extensions\particle.particle-vscode-core-1.13.1\node_modules\execa\lib\error.js:59:11)
    at handlePromise (c:\Users\user\.vscode\extensions\particle.particle-vscode-core-1.13.1\node_modules\execa\index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by hysteria9** [comment]
Just solved the problem. I was flashing using the name I gave to the photon instead of the ID. Thought it would work the same but apparently not.
